# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.3
loader_version=0.19.5
fabric_version=0.161.0+26.3
fabric.loom.disableObfuscation=true

# Mod Properties
mod_version=1.1.0
maven_group=org.steve
archives_base_name=SonicPulse

# Performance Settings
org.gradle.caching=true
org.gradle.vfs.watch=false
